### PR TITLE
update Hugo theme to Graphite

### PR DESCRIPTION
**Pull request by apreshill**
This PR updates the base Hugo theme to [Graphite](https://github.com/rstudio/hugo-graphite). It also:

+ bumps your Hugo version on Netlify to `0.71.1` (to allow the [header links](https://gohugo.io/getting-started/configuration-markup#heading-link-example))
+ adds a Hugo build command to match current `hugodown` netlify.toml template: https://github.com/r-lib/hugodown/blob/master/inst/templates/netlify.toml
+ restricts TOC printing to level 2 headers only (so `## Acknowledgements` will show up, but not `### Acknowledgements`)
+ moves custom archetype to project root (and removes the built-in theme archetype for blog content)

Here is what is new with the theme:

### New and improved features include:

* Gains tags for each blog post 
* Gains new taxonomy terms templates for [tags](https://hugo-graphite.netlify.app/tags/) and [categories](https://hugo-graphite.netlify.app/categories/)
* Gains a sticky Table of Contents for blog posts
* Gains copy-to-clipboard functionality for code chunks
* Gains anchorized header links
* Gains new shortcodes to create note and warning boxes
* Gains two new layout types ([**tutorial**](https://hugo-graphite.netlify.app/start/) and [**learn**](https://hugo-graphite.netlify.app/learn/))
* Better image accessibility
* Larger base font sizes for improved accessibility
* Many more parameters for customizing the site aesthetics

### Small tweaks

* Adds `target=_blank` to all external links
* Hexes on package pages are now symmetric
* Improved functioning for highlighting active menu items in the upper navbar (even with Hugo [nested sections](https://gohugo.io/content-management/sections/#nested-sections))
* JQuery upgrade
* Improved RSS feed handling (see: https://hugo-graphite.netlify.app/blog/index.xml)
* Improved sharing images for opengraph and twitter
* Styled footnotes from Goldmark Renderer
* Includes chroma CSS styles for highlighting via downlit for Hugodown sites
* Shiny new [demo site](https://hugo-graphite.netlify.app/)
* A new Hugo theme name that people can actually pronounce!

### CODE REVIEW

**Comment by apreshill** [comment]
The `learn` page currently has no TOC- by design:

```
<!----- CSS rules to get rid of CONTENTS header on this page only ---->
<style type = "text/css">
.hideOnMobile .sectionTitle {
    display: none;
}
</style>
```
Screen Shot 2020-07-06 at 2 24 18 PM

I know there is discussion around revising this section, but I'd suggest allowing the TOC. Now that it is sticky, perhaps more useful? Also consistent across the pages.

**Comment by hadley** [comment]
Yeah, I think we should remove the special-casing of the header on that page.

**Comment by hadley** [comment]
Is it worth deleting the `exampleSite` just to make the diff a little simpler?

**Comment by apreshill** [comment]
@hadley are you currently using this custom site archetype? 

https://github.com/tidyverse/tidyverse.org/tree/master/themes/hugo-tourmaline/archetypes/blog

I'm having trouble remembering the site-specific tweaks.

**Comment by hadley** [comment]
Yeah, definitely that custom archetype is what all posts start as.

**Comment by apreshill** [comment]
@hadley tested this solution and it works. I added the custom archetype to the project root, and removed the blog archetype from the theme since all our sites should use a custom one anyway. Hopefully this will make theme maintenance and debugging easier across the multiple sites.

**Comment by apreshill** [comment]
Here is the preview RSS feed, please check:

https://deploy-preview-456--tidyverse-org.netlify.app/blog/index.xml

**Comment by hadley** [comment]
RSS feed works in my feed reader.

**Comment by hadley** [comment]
From my perspective this looks good, and I'm happy to merge whenever you are.

**Comment by apreshill** [comment]
Ok we are done with tweaks (for now)- enjoy 🎉  (+ huge thx to @dcossyleon)

**Comment by hadley** [comment]
Thanks!!

**Pull request merged**
