### PR TITLE
Render bench 1.0.1 post with TOC

### PR DESCRIPTION
**Pull request by batpigandme**

### CODE REVIEW

**Comment by batpigandme** [comment]
Blurg! I have to figure out how to work around the diff. rendering of [`\@username`] with .Rmarkdown. From `.Rmd` this renders correctly, and _without_ the escape pandoc yells at you for not having a reference (thinking it's a citation). But, the markdown is rendered by Hugo with the `\` included…
image

**Comment by batpigandme** [comment]
Proposal (decidedly a function of laziness), we could just nix the usage of `@`. Since it's on a webpage, and not GH, it doesn't actually connect to anything special... 
cc @hadley

**Comment by hadley** [comment]
Another option would be to try `` `@blah` ``

**Comment by batpigandme** [comment]
You like? 
image

**Comment by hadley** [comment]
Hmmm, not really.

**Pull request closed without merging**
