### PR TITLE
typos in links

### PR DESCRIPTION
**Pull request by rosseji**

### CODE REVIEW

**Comment by rosseji** [comment]
I can see from the netlify that I'm missing a step to update something... hope that helps though

**Comment by rosseji** [comment]
I noticed that others don't have the same issue:
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">😮 and the thrills keep coming!<br>tidyeval &amp; tidyselect in tidyr: “tidyr 0.7.0” (officially tidy af) <a href="https://t.co/g846uySXpG">https://t.co/g846uySXpG</a> <a href="https://twitter.com/hashtag/rstats?src=hash">#rstats</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash">#tidyverse</a> <a href="https://t.co/k8qGy3fFi0">pic.twitter.com/k8qGy3fFi0</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/898297731453640704">August 17, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

But I see this:
screen shot 2017-08-18 at 7 42 18 am

**Comment by hadley** [comment]
Thanks for the fix!

You shouldn't knit, but instead run `blogdown::build_site()` - that preserves the blog post metadata.

**Comment by rosseji** [comment]
I've been playing around with `blogdown`...

But getting an error atm and thought I should be careful...

screen shot 2017-08-18 at 8 03 40 am

**Comment by hadley** [comment]
I haven't seen that before. @lionel- can you just fix directly please?

**Comment by rosseji** [comment]
``` r
sessionInfo()
#> R version 3.4.1 (2017-06-30)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Sierra 10.12.5
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.4.1  backports_1.1.0 magrittr_1.5    rprojroot_1.2  
#>  [5] tools_3.4.1     htmltools_0.3.6 yaml_2.1.14     Rcpp_0.12.12   
#>  [9] stringi_1.1.5   rmarkdown_1.6   knitr_1.17      stringr_1.2.0  
#> [13] digest_0.6.12   evaluate_0.10.1
```

**Comment by rosseji** [comment]
@hadley @lionel- 👌

**Comment by lionel-** [comment]
oops, should be fixed!

**Pull request closed without merging**
