### PR TITLE
Blog post for pillar 1.2.1

### PR DESCRIPTION
**Pull request by krlmlr**
@hadley: This requires a hotfix to be pushed to CRAN, to fix lubridate. I think the coloring of negative decimal numbers is wrong too.

Preview link: https://5a943d98efbe5d6bd34765fe--tidyverse-org.netlify.com/articles/2018/03/pillar-1-2-1/.

### CODE REVIEW

**Comment by hadley** [comment]
I think it might be easier for people to understand if you just use `tibble(x)` instead of `pillar(x)`

**Comment by krlmlr** [comment]
Thanks. Would you agree to an explanatory note? It seems that *ansistrings* can currently render *pillar* output but not *tibble* output (r-lib/ansistrings#14), and I'd rather avoid taking screenshots again.

**Comment by hadley** [comment]
Why is tibble not generated balanced escapes?

I'd really prefer to keep the blog post focussed on tibble, not on incidental details that most people won't care about.

**Comment by krlmlr** [comment]
*tibble* uses nested *crayon* styles which are implemented with escape codes. I might be able to work around this in *tibble*.

**Comment by krlmlr** [comment]
Changed examples to use *tibble*, added a clarification section to the bottom: https://deploy-preview-121--tidyverse-org.netlify.com/articles/2018/03/pillar-1-2-1/. Let's wait until Friday (the anticipated date of the blog post), binaries should be built by then.

**Comment by lionel-** [comment]
FYI I needed this tweak to `colourise_chunk()`:

```r
colourise_chunk <- function(type) {
  function(x, options) {
    x <- pkgdown:::escape_html(x)
    x <- ansistrings::ansi_to_html(x, fullpage = FALSE)
    class <- tolower(options$engine)
    sprintf('<pre class="knitr %s">%s</pre>\n', class, x)
  }
}
```

It escapes HTML syntax which is necessary for printing stuff like `<quosure>`.

**Comment by krlmlr** [comment]
Thanks. I'm already using `htmltools::htmlEscape(x)` in the call to `ansi_to_html()`, the code looks very similar to yours.

**Comment by lionel-** [comment]
oops sorry I must have been confused while debugging and somehow got rid of `htmltools::htmlEscape()`

**Comment by krlmlr** [comment]
All binaries have been built on CRAN, ready to publish?

**Comment by hadley** [comment]
Published, thanks!

**Pull request merged**
