### PR TITLE
Moar hexes

### PR DESCRIPTION
**Pull request by apreshill**
This PR is a minor Hugo graphite theme update. It adds:

+ 2 more hexes to the homepage (in band 1)
+ alt text to the cover image (in band 2)
+ a `packages.yml` that now populates the packages page via a shortcode (so we don't need to edit raw html with deeply nested divs)
+ fixes the issue @lionel- ran into with the partial meta layout file with no images in the post bundle
+ minor CSS updates and layout fixes that came up in testing other sites

### CODE REVIEW

**Comment by hadley** [comment]
Does this fix #212?

**Comment by hadley** [comment]
BTW it'd be better to not hot-linking to the logos on hex-stickers because they're high-res versions that are often 2+ MB! 😱

**Comment by apreshill** [comment]
Hi @hadley - this does fix #212 and #461. I updated to make all hex images self hosted now, as opposed to hot linked, on the homepage and the packages page.

**Comment by hadley** [comment]
Looks awesome, thanks!

**Pull request merged**
