### PR TITLE
Add TDD Toulouse post.

### PR DESCRIPTION
**Pull request by batpigandme**

### CODE REVIEW

**Comment by batpigandme** [comment]
Things I currently dislike about this post but cannot for the life of me figure out right now…

- [ ] The title is visually irksome
- [ ] The bullets really aren't bullets
- [ ] The description
- [ ] The scope is wildly unclear
- [ ] The voice: I wasn't there, and I reworked things way too many times, and now diff. parts imply diff. things (possibly)

**Comment by hadley** [comment]
I've fetch locally and I'll make some changes.

**Comment by hadley** [comment]
Ok, I did some reshuffling to make it flow a bit better. I think you should do one more round of proof reading to fix the mistakes that I've undoubtedly added and then publish it.

**Comment by batpigandme** [comment]
@hadley, I added you as an author, since you took/take care of the passive-voice problem (in your edits, and by literally being there). I'll merge in a couple hours.

**Pull request merged**
