### PR TITLE
is vroom part of tidyverse?

### PR DESCRIPTION
**Pull request by wibeasley**

### CODE REVIEW

**Comment by batpigandme** [comment]
Nope it's in r-lib https://vroom.r-lib.org/

**Comment by batpigandme** [comment]
Thanks, though.

**Comment by hadley** [comment]
And vroom is going to get integrated in readr in the not too distant future.

**Comment by wibeasley** [comment]
oh, that's good to know.  Thanks for the heads up.  I've been writing a lot of vroom code recently when readr would have worked just as well.  I'll go back to readr (for the small datasets) so I don't need to update the code later.

**Pull request closed without merging**
