### PR TITLE
Lifecycle 1.0.0

### PR DESCRIPTION
**Pull request by hadley**
* [x] `usethis::use_tidy_thanks()`
* [x] update date
* [x] add link to release notes

Main question: do you think I'm missing an opportunity to explain the lifecycle directly in the post?

### CODE REVIEW

**Comment by hadley** [comment]
Scheduled lifecycle for release on Feb 12.

**Comment by jennybc** [comment]
It feels like the writing / talking you've already done is sufficient and that pointing towards those resources is OK.

**Review by jennybc — APPROVED** [review]

**Comment by lorenzwalthert** [comment]
Aren’t there a few dots missing in the title? 
36E6C766-5ACB-4C17-BAE4-C9DC034B2871

**Comment by hadley** [comment]
@lorenzwalthert fixed thanks

**Pull request merged**
